<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Exposure-adjusted road collision risk modelling for Great Britain">

<title>Joining Road Safety Datasets – Open Road Risk</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-61737856611e025524b03b0d840573db.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WD8T0TPHC5"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WD8T0TPHC5', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Joining Road Safety Datasets – Open Road Risk">
<meta property="og:description" content="How collision, traffic, road network, and contextual datasets are joined into link-level and link-year modelling tables.">
<meta property="og:image" content="https://openroadrisk.org/outputs/figures/snap-example-simple.png">
<meta property="og:site_name" content="Open Road Risk">
<meta property="og:image:alt" content="Simple STATS19 snapping example showing nearby grey road links, a red selected road link, and a blue collision point.">
<meta property="og:image:height" content="818">
<meta property="og:image:width" content="676">
<meta name="twitter:title" content="Joining Road Safety Datasets – Open Road Risk">
<meta name="twitter:description" content="How collision, traffic, road network, and contextual datasets are joined into link-level and link-year modelling tables.">
<meta name="twitter:image" content="https://openroadrisk.org/outputs/figures/snap-example-simple.png">
<meta name="twitter:image:alt" content="Simple STATS19 snapping example showing nearby grey road links, a red selected road link, and a blue collision point.">
<meta name="twitter:image-height" content="818">
<meta name="twitter:image-width" content="676">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Open Road Risk</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-project" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-project">    
        <li>
    <a class="dropdown-item" href="../project/project-overview.html">
 <span class="dropdown-text">Project overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project/model-status.html">
 <span class="dropdown-text">Current model status</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project/ai-assisted-development.html">
 <span class="dropdown-text">AI-assisted development</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-literature" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Literature</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-literature">    
        <li>
    <a class="dropdown-item" href="../literature/literature-index.html">
 <span class="dropdown-text">Literature overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/literature-evidence-register.html">
 <span class="dropdown-text">Literature evidence register</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project/ai-assisted-domain-knowledge.html">
 <span class="dropdown-text">AI-assisted literature review</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/literature-pipeline-alignment.html">
 <span class="dropdown-text">Literature-pipeline alignment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/crash-frequency-models.html">
 <span class="dropdown-text">Crash frequency models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/exposure-and-traffic-volume.html">
 <span class="dropdown-text">Exposure and traffic volume</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/spatial-methods-and-network-risk.html">
 <span class="dropdown-text">Spatial methods and network risk</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/junctions-and-conflict-structure.html">
 <span class="dropdown-text">Junctions and conflict structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/severity-modelling.html">
 <span class="dropdown-text">Severity modelling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/validation-and-metrics.html">
 <span class="dropdown-text">Validation and metrics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../literature/transferability-and-open-data-limits.html">
 <span class="dropdown-text">Transferability and open data limits</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-sources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Sources</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-sources">    
        <li>
    <a class="dropdown-item" href="../data-sources/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/stats19.html">
 <span class="dropdown-text">STATS19 Collisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/openroads.html">
 <span class="dropdown-text">OS Open Roads</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/aadf.html">
 <span class="dropdown-text">AADF Traffic Counts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/webtris.html">
 <span class="dropdown-text">WebTRIS Sensors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/network-model-gdb.html">
 <span class="dropdown-text">Network Model GDB</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/terrain.html">
 <span class="dropdown-text">OS Terrain 50 (grade)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-sources/deprivation.html">
 <span class="dropdown-text">Deprivation (IoD 2025)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="../methodology/methodology-index.html">
 <span class="dropdown-text">Methodology Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/data-joining.html">
 <span class="dropdown-text">Joining the Datasets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/feature-engineering.html">
 <span class="dropdown-text">Feature Engineering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/empirical-bayes-shrinkage.html">
 <span class="dropdown-text">Empirical Bayes Shrinkage</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-exploratory-data-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Exploratory Data Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-exploratory-data-analysis">    
        <li>
    <a class="dropdown-item" href="../analysis/eda-collisions.html">
 <span class="dropdown-text">Collision EDA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/collision-exposure-behaviour.html">
 <span class="dropdown-text">Collision-Exposure Behaviour</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/vehicle-mix.html">
 <span class="dropdown-text">Vehicle Mix Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/road-curvature.html">
 <span class="dropdown-text">Road Curvature</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/temporal-exploration.html">
 <span class="dropdown-text">Months and Days of Week</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/eda-traffic.html">
 <span class="dropdown-text">Traffic Volume EDA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/osm-coverage.html">
 <span class="dropdown-text">OSM Coverage</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-models" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-models">    
        <li>
    <a class="dropdown-item" href="../methodology/modelling.html">
 <span class="dropdown-text">Modelling Approach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/exposure-model.html">
 <span class="dropdown-text">Stage 1a: Traffic Volume</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/timezone-profile.html">
 <span class="dropdown-text">Stage 1b: Time-Zone Profiles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../analysis/model-results.html">
 <span class="dropdown-text">Stage 2: Collision Risk Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/facility-family-split.html">
 <span class="dropdown-text">Facility Family Split</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methodology/model-inventory.html">
 <span class="dropdown-text">Model Inventory</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-investigations" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Investigations</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-investigations">    
        <li>
    <a class="dropdown-item" href="../investigations/index.html">
 <span class="dropdown-text">Investigations overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/ksi-atlas.html">
 <span class="dropdown-text">KSI atlas diagnostic</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/staffordshire-data-quality.html">
 <span class="dropdown-text">Staffordshire data quality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/temporal-descriptors.html">
 <span class="dropdown-text">Temporal descriptors evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/aadf-counted-only-filter.html">
 <span class="dropdown-text">AADF counted-only filter</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/rank-stability.html">
 <span class="dropdown-text">Rank stability harness</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../investigations/zero-calibration.html">
 <span class="dropdown-text">Zero-calibration diagnostic</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outputs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outputs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outputs">    
        <li>
    <a class="dropdown-item" href="../outputs/key-figures.html">
 <span class="dropdown-text">Key figures</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../outputs/top-risk-map.html">
 <span class="dropdown-text">Top-risk map</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../tools/ukgeo.html">
 <span class="dropdown-text">ukgeo — UK Geocoder</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../future-work.html"> 
<span class="menu-text">Future Work</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/thomashsimm/open-road-risk"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-joining-is-the-hard-part" id="toc-why-joining-is-the-hard-part" class="nav-link active" data-scroll-target="#why-joining-is-the-hard-part"><span class="header-section-number">1</span> Why joining is the hard part</a></li>
  <li><a href="#what-this-page-answers" id="toc-what-this-page-answers" class="nav-link" data-scroll-target="#what-this-page-answers"><span class="header-section-number">2</span> What this page answers</a></li>
  <li><a href="#pipeline-overview" id="toc-pipeline-overview" class="nav-link" data-scroll-target="#pipeline-overview"><span class="header-section-number">3</span> Pipeline overview</a></li>
  <li><a href="#stage-1-stats19-cleaning" id="toc-stage-1-stats19-cleaning" class="nav-link" data-scroll-target="#stage-1-stats19-cleaning"><span class="header-section-number">4</span> Stage 1: STATS19 cleaning</a>
  <ul class="collapse">
  <li><a href="#coordinate-validation" id="toc-coordinate-validation" class="nav-link" data-scroll-target="#coordinate-validation"><span class="header-section-number">4.1</span> Coordinate validation</a></li>
  <li><a href="#road-name-reconstruction" id="toc-road-name-reconstruction" class="nav-link" data-scroll-target="#road-name-reconstruction"><span class="header-section-number">4.2</span> Road name reconstruction</a></li>
  <li><a href="#covid-flag" id="toc-covid-flag" class="nav-link" data-scroll-target="#covid-flag"><span class="header-section-number">4.3</span> COVID flag</a></li>
  </ul></li>
  <li><a href="#stage-2-snapping-collisions-to-road-links" id="toc-stage-2-snapping-collisions-to-road-links" class="nav-link" data-scroll-target="#stage-2-snapping-collisions-to-road-links"><span class="header-section-number">5</span> Stage 2: Snapping collisions to road links</a>
  <ul class="collapse">
  <li><a href="#why-nearest-neighbour-fails" id="toc-why-nearest-neighbour-fails" class="nav-link" data-scroll-target="#why-nearest-neighbour-fails"><span class="header-section-number">5.1</span> Why nearest-neighbour fails</a></li>
  <li><a href="#densification-25-m-interpolation-along-each-link" id="toc-densification-25-m-interpolation-along-each-link" class="nav-link" data-scroll-target="#densification-25-m-interpolation-along-each-link"><span class="header-section-number">5.2</span> Densification: 25 m interpolation along each link</a></li>
  <li><a href="#candidate-selection" id="toc-candidate-selection" class="nav-link" data-scroll-target="#candidate-selection"><span class="header-section-number">5.3</span> Candidate selection</a></li>
  <li><a href="#scoring-four-dimensions" id="toc-scoring-four-dimensions" class="nav-link" data-scroll-target="#scoring-four-dimensions"><span class="header-section-number">5.4</span> Scoring: four dimensions</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output"><span class="header-section-number">5.5</span> Output</a></li>
  <li><a href="#the-0.6-threshold" id="toc-the-0.6-threshold" class="nav-link" data-scroll-target="#the-0.6-threshold"><span class="header-section-number">5.6</span> The 0.6 threshold</a></li>
  <li><a href="#worked-graphical-examples" id="toc-worked-graphical-examples" class="nav-link" data-scroll-target="#worked-graphical-examples"><span class="header-section-number">5.7</span> Worked graphical examples</a></li>
  <li><a href="#fallback-snap_quick-and-snap_collisions_to_roads" id="toc-fallback-snap_quick-and-snap_collisions_to_roads" class="nav-link" data-scroll-target="#fallback-snap_quick-and-snap_collisions_to_roads"><span class="header-section-number">5.8</span> Fallback: <code>snap_quick</code> and <code>snap_collisions_to_roads</code></a></li>
  </ul></li>
  <li><a href="#stage-3-webtris-aadf" id="toc-stage-3-webtris-aadf" class="nav-link" data-scroll-target="#stage-3-webtris-aadf"><span class="header-section-number">6</span> Stage 3: WebTRIS → AADF</a>
  <ul class="collapse">
  <li><a href="#why-nullify-beyond-the-cap" id="toc-why-nullify-beyond-the-cap" class="nav-link" data-scroll-target="#why-nullify-beyond-the-cap"><span class="header-section-number">6.1</span> Why nullify beyond the cap?</a></li>
  </ul></li>
  <li><a href="#stage-4-aadf-road-links" id="toc-stage-4-aadf-road-links" class="nav-link" data-scroll-target="#stage-4-aadf-road-links"><span class="header-section-number">7</span> Stage 4: AADF → road links</a>
  <ul class="collapse">
  <li><a href="#distance-cap-2-km" id="toc-distance-cap-2-km" class="nav-link" data-scroll-target="#distance-cap-2-km"><span class="header-section-number">7.1</span> Distance cap: 2 km</a></li>
  <li><a href="#street-name-fallback" id="toc-street-name-fallback" class="nav-link" data-scroll-target="#street-name-fallback"><span class="header-section-number">7.2</span> Street-name fallback</a></li>
  <li><a href="#what-this-means-for-the-model" id="toc-what-this-means-for-the-model" class="nav-link" data-scroll-target="#what-this-means-for-the-model"><span class="header-section-number">7.3</span> What this means for the model</a></li>
  </ul></li>
  <li><a href="#stage-5-aggregation-to-link-year" id="toc-stage-5-aggregation-to-link-year" class="nav-link" data-scroll-target="#stage-5-aggregation-to-link-year"><span class="header-section-number">8</span> Stage 5: Aggregation to link × year</a>
  <ul class="collapse">
  <li><a href="#filtering-snapped-collisions" id="toc-filtering-snapped-collisions" class="nav-link" data-scroll-target="#filtering-snapped-collisions"><span class="header-section-number">8.1</span> Filtering snapped collisions</a></li>
  <li><a href="#per-link-aggregation" id="toc-per-link-aggregation" class="nav-link" data-scroll-target="#per-link-aggregation"><span class="header-section-number">8.2</span> Per-link aggregation</a></li>
  <li><a href="#joining-road-attributes" id="toc-joining-road-attributes" class="nav-link" data-scroll-target="#joining-road-attributes"><span class="header-section-number">8.3</span> Joining road attributes</a></li>
  <li><a href="#final-rate-calculation" id="toc-final-rate-calculation" class="nav-link" data-scroll-target="#final-rate-calculation"><span class="header-section-number">8.4</span> Final rate calculation</a></li>
  </ul></li>
  <li><a href="#quality-tracking" id="toc-quality-tracking" class="nav-link" data-scroll-target="#quality-tracking"><span class="header-section-number">9</span> Quality tracking</a></li>
  <li><a href="#quick-vs-weighted-comparison" id="toc-quick-vs-weighted-comparison" class="nav-link" data-scroll-target="#quick-vs-weighted-comparison"><span class="header-section-number">10</span> Quick-vs-weighted comparison</a></li>
  <li><a href="#known-issues-and-tradeoffs" id="toc-known-issues-and-tradeoffs" class="nav-link" data-scroll-target="#known-issues-and-tradeoffs"><span class="header-section-number">11</span> Known issues and tradeoffs</a>
  <ul class="collapse">
  <li><a href="#weights-are-fixed-not-learned" id="toc-weights-are-fixed-not-learned" class="nav-link" data-scroll-target="#weights-are-fixed-not-learned"><span class="header-section-number">11.1</span> Weights are fixed, not learned</a></li>
  <li><a href="#distance-caps-are-empirical" id="toc-distance-caps-are-empirical" class="nav-link" data-scroll-target="#distance-caps-are-empirical"><span class="header-section-number">11.2</span> Distance caps are empirical</a></li>
  <li><a href="#error-compounding-across-stages" id="toc-error-compounding-across-stages" class="nav-link" data-scroll-target="#error-compounding-across-stages"><span class="header-section-number">11.3</span> Error compounding across stages</a></li>
  <li><a href="#road-name-normalisation-is-strict" id="toc-road-name-normalisation-is-strict" class="nav-link" data-scroll-target="#road-name-normalisation-is-strict"><span class="header-section-number">11.4</span> Road name normalisation is strict</a></li>
  <li><a href="#dual-carriageways" id="toc-dual-carriageways" class="nav-link" data-scroll-target="#dual-carriageways"><span class="header-section-number">11.5</span> Dual carriageways</a></li>
  <li><a href="#coordinate-source-limitations" id="toc-coordinate-source-limitations" class="nav-link" data-scroll-target="#coordinate-source-limitations"><span class="header-section-number">11.6</span> Coordinate-source limitations</a></li>
  </ul></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps"><span class="header-section-number">12</span> Next steps</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Joining Road Safety Datasets</h1>
</div>

<div>
  <div class="description">
    How collision, traffic, road network, and contextual datasets are joined into link-level and link-year modelling tables.
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<section id="why-joining-is-the-hard-part" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="why-joining-is-the-hard-part"><span class="header-section-number">1</span> Why joining is the hard part</h2>
<p>The model target — collision rate per road link per year — does not exist in any single dataset. It has to be constructed by joining three sources that were never designed to be combined:</p>
<ul>
<li><strong>STATS19 collisions</strong> are points with GPS coordinates and a police-recorded road name.</li>
<li><strong>AADF traffic counts</strong> are points at DfT count-point locations, keyed by <code>count_point_id</code>.</li>
<li><strong>WebTRIS sensors</strong> are points on the National Highways network, keyed by <code>site_id</code>.</li>
<li><strong>OS Open Roads links</strong> are line geometries with a <code>link_id</code> and a <code>road_classification</code>.</li>
</ul>
<p>No shared key links them. Every connection has to be inferred from spatial proximity, road names, or both.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The joining stage is where most of the signal is gained or lost.</strong> A collision snapped to the wrong road changes both its traffic denominator and the road attributes it inherits. Under-reporting aside, snap quality is the dominant source of noise in the final rates.</p>
</div>
</div>
</section>
<section id="what-this-page-answers" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="what-this-page-answers"><span class="header-section-number">2</span> What this page answers</h2>
<ol type="1">
<li>What is being joined, and in what order?</li>
<li>How are collisions matched to road links, given that two collisions 10m apart might belong to an A-road and a parallel B-road?</li>
<li>How are traffic counts attached to road links when AADF count points are sparse and WebTRIS sensors are even sparser?</li>
<li>What happens to data beyond the distance caps, and why not just pick the nearest match?</li>
<li>How is match confidence tracked and used?</li>
</ol>
<hr>
</section>
<section id="pipeline-overview" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="pipeline-overview"><span class="header-section-number">3</span> Pipeline overview</h2>
<p>The joining pipeline runs in five stages, implemented across <code>clean.py</code>, <code>snap.py</code>, and <code>join.py</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Input</th>
<th>Output</th>
<th>Join method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Clean STATS19</td>
<td>Raw collision CSVs</td>
<td>Validated collisions with <code>road_name_clean</code></td>
<td>LSOA coordinate check</td>
</tr>
<tr class="even">
<td>2. Snap collisions to links</td>
<td>Collisions + OS Open Roads</td>
<td>Collisions with <code>link_id</code> + <code>snap_score</code></td>
<td>Weighted multi-criteria</td>
</tr>
<tr class="odd">
<td>3. Attach WebTRIS to AADF</td>
<td>AADF + WebTRIS</td>
<td>AADF with sensor features</td>
<td>Spatial nearest (5 km cap)</td>
</tr>
<tr class="even">
<td>4. Attach AADF to road links</td>
<td>Road links + (AADF + WebTRIS)</td>
<td>Road features per link × year</td>
<td>Spatial nearest (2 km cap)</td>
</tr>
<tr class="odd">
<td>5. Aggregate to link × year</td>
<td>Snapped collisions + road features</td>
<td><code>road_link_annual.parquet</code></td>
<td>Key join on <code>link_id × year</code></td>
</tr>
</tbody>
</table>
<p>Each stage preserves confidence information — snap scores, distances, join methods, availability flags — so the feature engineering can filter on quality.</p>
<hr>
</section>
<section id="stage-1-stats19-cleaning" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="stage-1-stats19-cleaning"><span class="header-section-number">4</span> Stage 1: STATS19 cleaning</h2>
<p>Collision cleaning happens in <code>clean_stats19()</code> and does three things that matter for the joins downstream.</p>
<section id="coordinate-validation" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="coordinate-validation"><span class="header-section-number">4.1</span> Coordinate validation</h3>
<p>Police-recorded lat/lon is generally reliable across Yorkshire forces, but a small number of records have systematic errors. The pipeline validates each collision’s coordinates against its <strong>recorded LSOA centroid</strong> using haversine distance:</p>
<ul>
<li>Collisions more than 10 km from their LSOA centroid are flagged as <code>coords_suspect = True</code>.</li>
<li>Records outside the GB bounding box are flagged as <code>coords_valid = False</code>.</li>
</ul>
<p>Flagged records are <strong>not dropped</strong> — they remain available for non-spatial analysis — but they are excluded from the spatial snap.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spatial snapping uses STATS19 <code>latitude</code> / <code>longitude</code>, not <code>location_easting_osgr</code> / <code>location_northing_osgr</code>. A previous notebook suspected a Yorkshire BNG grid-square error, but a direct check against the current raw DfT STATS19 CSV found no systematic mismatch: Yorkshire BNG fields agree with lat/lon-derived BNG positions within a few metres.</p>
</div>
</div>
</section>
<section id="road-name-reconstruction" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="road-name-reconstruction"><span class="header-section-number">4.2</span> Road name reconstruction</h3>
<p>STATS19 encodes road classification and number separately: <code>first_road_class</code> (integer code) and <code>first_road_number</code>. These are reconstructed into a single string:</p>
<pre><code>class=1, number=62    → "M62"
class=3, number=64    → "A64"
class=4, number=1234  → "B1234"
class=6               → ""   (unclassified, no named road)</code></pre>
<p>The result is stored as <code>road_name_clean</code> and feeds one of the four scoring dimensions in Stage 2.</p>
</section>
<section id="covid-flag" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="covid-flag"><span class="header-section-number">4.3</span> COVID flag</h3>
<p><code>is_covid = True</code> for collisions in 2020 or 2021. Carried through all downstream tables so the modelling code can optionally exclude or separately model these years.</p>
<hr>
</section>
</section>
<section id="stage-2-snapping-collisions-to-road-links" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="stage-2-snapping-collisions-to-road-links"><span class="header-section-number">5</span> Stage 2: Snapping collisions to road links</h2>
<p>This is the hardest join in the pipeline. A collision on a named road must be attached to the correct road link — and GPS noise, carriageway separation, and parallel minor roads all make this non-trivial.</p>
<section id="why-nearest-neighbour-fails" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="why-nearest-neighbour-fails"><span class="header-section-number">5.1</span> Why nearest-neighbour fails</h3>
<p>A naive nearest-neighbour snap fails in several common cases:</p>
<ul>
<li><strong>Parallel roads.</strong> A collision on the M1 might be geometrically closer to a B-road running alongside than to the motorway itself.</li>
<li><strong>Dual carriageways.</strong> The two carriageways are separate OS Open Roads links; a collision reported on one side may snap to the other.</li>
<li><strong>GPS drift.</strong> Police-recorded coordinates can drift 20–50 m from the carriageway, especially on urban roads with tall buildings.</li>
<li><strong>Long links with centroid-based indexing.</strong> A 2 km motorway link has a centroid that could be 800 m from a collision 20 m off the road.</li>
</ul>
<p>Snap.py addresses all four with two co-designed pieces: <strong>link densification</strong> for the spatial index, and <strong>multi-criteria scoring</strong> for disambiguation.</p>
</section>
<section id="densification-25-m-interpolation-along-each-link" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="densification-25-m-interpolation-along-each-link"><span class="header-section-number">5.2</span> Densification: 25 m interpolation along each link</h3>
<p>Before any matching, every OS Open Roads link is sampled at 25 m intervals along its LineString geometry. A 2 km motorway link becomes ~80 points; a 20 m urban link becomes 2 points. All densified points carry their parent <code>link_id</code>.</p>
<p>The KD-tree is built on these densified points, not on link centroids. This means a collision 20 m from the road will always find a candidate point within 25 m — regardless of link length.</p>
</section>
<section id="candidate-selection" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="candidate-selection"><span class="header-section-number">5.3</span> Candidate selection</h3>
<p>For each collision, the KD-tree returns the <strong>K = 20 nearest densified points</strong> within a <strong>500 m search radius</strong>. Points are deduplicated to their parent links; the closest point per link is retained as that link’s candidate distance. The result is a set of up to 20 candidate links per collision.</p>
</section>
<section id="scoring-four-dimensions" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="scoring-four-dimensions"><span class="header-section-number">5.4</span> Scoring: four dimensions</h3>
<p>Each candidate link is scored on four dimensions. The composite score is a weighted sum with weights fixed at</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Weight</th>
<th>What it measures</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spatial</td>
<td>40%</td>
<td>Distance from collision to link, exponential decay</td>
</tr>
<tr class="even">
<td>Road classification</td>
<td>25%</td>
<td>STATS19 <code>first_road_class</code> vs OS <code>road_classification</code></td>
</tr>
<tr class="odd">
<td>Junction / form of way</td>
<td>25%</td>
<td>STATS19 <code>junction_detail</code> vs OS <code>form_of_way</code></td>
</tr>
<tr class="even">
<td>Road number</td>
<td>10%</td>
<td>STATS19 reconstructed road name vs OS <code>road_name_clean</code></td>
</tr>
</tbody>
</table>
<section id="spatial-score" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="spatial-score"><span class="header-section-number">5.4.1</span> Spatial score</h4>
<p><span class="math display">\[
s_\text{spatial}(d) = \exp\!\left(-\frac{d \log 2}{100}\right)
\]</span></p>
<p>Exponential decay with a 100 m half-life. Concretely: 100 m → 0.50, 200 m → 0.25, 500 m → 0.03. Spatial score alone is not enough — a collision 30 m off an M-road will have a high spatial score against both the M-road link and an adjacent A-road link.</p>
</section>
<section id="road-classification-score" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="road-classification-score"><span class="header-section-number">5.4.2</span> Road classification score</h4>
<p>Each STATS19 road class (1 = Motorway, 2 = A(M), 3 = A, 4 = B, 5 = C, 6 = unclassified) has preferred / partial / penalty sets of OS classifications. Example for class 1 (Motorway):</p>
<ul>
<li><strong>preferred (1.0):</strong> <code>Motorway</code></li>
<li><strong>partial (0.5):</strong> <code>A Road</code></li>
<li><strong>penalty (0.0):</strong> <code>B Road</code>, <code>Unclassified</code>, etc.</li>
</ul>
<p>Candidates not in any of the three sets score 0.5 (neutral).</p>
</section>
<section id="junction-form-of-way-score" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="junction-form-of-way-score"><span class="header-section-number">5.4.3</span> Junction / form-of-way score</h4>
<p>Uses <code>junction_detail</code> to constrain <code>form_of_way</code>. Key cases:</p>
<ul>
<li><code>junction_detail = 0</code> (not at a junction) <strong>penalises</strong> Slip Road and Roundabout candidates.</li>
<li><code>junction_detail = 18</code> (private drive) <strong>penalises</strong> Motorway and Slip Road.</li>
<li><code>junction_detail = 99</code> or <code>-1</code> (unknown) applies no constraint.</li>
</ul>
</section>
<section id="road-number-score" class="level4" data-number="5.4.4">
<h4 data-number="5.4.4" class="anchored" data-anchor-id="road-number-score"><span class="header-section-number">5.4.4</span> Road number score</h4>
<p>Exact string match on <code>road_name_clean</code>. Low weight (10%) because the STATS19 road number field has well-known quality issues — it’s often missing or mis-entered. Treated as:</p>
<ul>
<li><strong>1.0</strong> — exact match (e.g.&nbsp;STATS19 “M62” ↔︎ OS “M62”)</li>
<li><strong>0.5</strong> — STATS19 has no road number, or OS link has no road name (can’t contradict)</li>
<li><strong>0.1</strong> — mismatch</li>
</ul>
</section>
</section>
<section id="output" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="output"><span class="header-section-number">5.5</span> Output</h3>
<p>The top-scoring candidate is returned per collision. The output carries every per-dimension score as well as the composite:</p>
<ul>
<li><code>link_id</code>, <code>snap_distance_m</code>, <code>snap_score</code></li>
<li><code>score_spatial</code>, <code>score_class</code>, <code>score_junction</code>, <code>score_number</code></li>
<li><code>snap_method ∈ {weighted, invalid_coords, unmatched}</code></li>
</ul>
</section>
<section id="the-0.6-threshold" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="the-0.6-threshold"><span class="header-section-number">5.6</span> The 0.6 threshold</h3>
<p>In <code>join.py</code>, only collisions with <code>snap_score &gt;= 0.6</code> are retained in the link-year aggregation. The threshold is empirical — chosen so the retained count matches a baseline from earlier pipeline versions.</p>
<p>The practical meaning of 0.6 depends on how the score components combine. With neutral (0.5) scores on class, junction, and number, a composite of 0.6 requires spatial ≈ 0.75 — about <strong>42 m</strong> by the exponential decay. With strongly-matching attributes, spatial can be much lower and still pass.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 0.6 threshold trades off recall against precision. Lowering it recovers more collisions (including correctly-matched ones at longer distances) but introduces more errors on dense multi-road areas. It has not been formally optimised against a gold-standard labelled set.</p>
</div>
</div>
</section>
<section id="worked-graphical-examples" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="worked-graphical-examples"><span class="header-section-number">5.7</span> Worked graphical examples</h3>
<p>The examples below show the spatial decision being made. The highlighted alternatives are nearby candidate links reconstructed for explanation; the exact internal candidate list is not stored in the final snapped output. The aim is to show why snapping quality matters before collisions are aggregated to road-link × year.</p>
<p>STATS19 collisions are point records, while the model needs counts on <code>link_id × year</code>. Snapping assigns each point to a plausible OS Open Roads link, then the retained snapped collisions are aggregated by <code>link_id × year</code> before joining to AADT, road geometry, and context features. Near junctions, dual carriageways, and dense urban networks, this is necessarily a spatial approximation rather than a literal observation of the carriageway used. Low-confidence, invalid, or unmatched records are filtered or handled separately before rate modelling.</p>
<p>The figures are generated statically by <code>src/road_risk/outputs/build_snap_example_figures.py</code> from existing processed outputs. Grey lines are nearby OS Open Roads candidates, red is the selected snapped link, and the blue point is the original STATS19 collision location. Orange and purple links mark the next two reconstructed nearby candidates shown for context. The labels <code>S</code>, <code>2</code>, and <code>3</code> identify the selected link and the two highlighted alternatives; the dashed blue line shows the snap offset. The compact scoring tables below are reconstructed explanatory candidate tables: they reuse the weighted snap scoring functions, but the final snapped parquet stores exact component scores only for the selected link, not for every losing candidate.</p>
<p>Small schematic of the weighted snap:</p>
<p><code>STATS19 point</code> → <code>find nearby densified Open Roads candidates</code> → <code>score candidates</code> → <code>keep highest scoring link</code> → <code>apply 0.6 threshold</code> → <code>aggregate retained collisions to link_id × year</code></p>
<p>The first table is source-row context from the cleaned STATS19 collision parquet. These fields are not the snap output: they are the original collision row values carried through cleaning, shown here for the six example rows chosen by the figure script.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Example type</th>
<th>Original STATS19 row context</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple road segment</td>
<td><code>collision_index=2022501162401</code>; 2022-04-04 07:59; severity Slight; 2 vehicles, 1 casualty; first road A38; single carriageway; 50 mph; not at junction or within 20 metres; raining, no high winds; wet or damp; point (-4.349419, 50.407907).</td>
</tr>
<tr class="even">
<td>Junction or roundabout</td>
<td><code>collision_index=20171341K0936</code>; 2017-01-20 12:00; severity Slight; 2 vehicles, 1 casualty; first road A650; roundabout; 60 mph; STATS19 <code>junction_detail=0</code> (not at junction or within 20 metres); fine, no high winds; dry; point (-1.520043, 53.708393).</td>
</tr>
<tr class="odd">
<td>Dual carriageway / parallel links</td>
<td><code>collision_index=2018200265540</code>; 2018-01-23 14:35; severity Slight; 2 vehicles, 3 casualties; first road A4540; road type roundabout; 40 mph; second road A38; raining, no high winds; wet or damp; point (-1.888107, 52.491773).</td>
</tr>
<tr class="even">
<td>Dense urban network</td>
<td><code>collision_index=2019051912399</code>; 2019-09-19 18:00; severity Slight; 2 vehicles, 1 casualty; first road unclassified; single carriageway; 30 mph; STATS19 <code>junction_detail=13</code> in the cleaned row; fine, no high winds; dry; point (-3.038868, 53.430502).</td>
</tr>
<tr class="odd">
<td>Lower-confidence retained snap</td>
<td><code>collision_index=2023010445298</code>; 2023-05-26 19:03; severity Slight; 1 vehicle, 1 casualty; first road class C with no road number; single carriageway; 20 mph; not at junction or within 20 metres; fine, no high winds; dry; point (-0.249922, 51.516427).</td>
</tr>
<tr class="even">
<td>Filtered low-score snap</td>
<td><code>collision_index=2015950000240</code>; 2015-01-22 08:05; severity Serious; 2 vehicles, 1 casualty; first road B1345; single carriageway; 60 mph; not at junction or within 20 metres; fine, no high winds; wet or damp; point (-2.746766, 56.055312).</td>
</tr>
</tbody>
</table>
<p>The next table is snap-output traceability from <code>quarto/outputs/figures/snap-examples-manifest.json</code>. It shows what the snap step produced for those same STATS19 rows, including the selected OS Open Roads <code>link_id</code> and whether the row is retained for link-year aggregation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Example type</th>
<th>STATS19 collision_index</th>
<th style="text-align: right;">Year</th>
<th>Snap method</th>
<th style="text-align: right;">Score</th>
<th style="text-align: right;">Distance</th>
<th>Selected link id</th>
<th style="text-align: right;">Candidates shown</th>
<th>Status</th>
<th>What this shows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple road segment</td>
<td><code>2022501162401</code></td>
<td style="text-align: right;">2022</td>
<td>weighted</td>
<td style="text-align: right;">0.861</td>
<td style="text-align: right;">5.0 m</td>
<td><code>65BCF56A-4692-46C5-AF86-284DA73DF77E</code></td>
<td style="text-align: right;">3</td>
<td>retained</td>
<td>One nearby link clearly fits the point and road attributes.</td>
</tr>
<tr class="even">
<td>Junction or roundabout</td>
<td><code>20171341K0936</code></td>
<td style="text-align: right;">2017</td>
<td>weighted</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.0 m</td>
<td><code>E43FE188-A37C-4085-BC80-8F3009AD643C</code></td>
<td style="text-align: right;">17</td>
<td>retained</td>
<td>Near a junction, several short links can be plausible.</td>
</tr>
<tr class="odd">
<td>Dual carriageway / parallel links</td>
<td><code>2018200265540</code></td>
<td style="text-align: right;">2018</td>
<td>weighted</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.0 m</td>
<td><code>7DF69055-C6EC-459B-AD10-3C683FFCD19E</code></td>
<td style="text-align: right;">59</td>
<td>retained</td>
<td>Parallel carriageways make distance-only snapping ambiguous.</td>
</tr>
<tr class="even">
<td>Dense urban network</td>
<td><code>2019051912399</code></td>
<td style="text-align: right;">2019</td>
<td>weighted</td>
<td style="text-align: right;">0.950</td>
<td style="text-align: right;">0.0 m</td>
<td><code>0370946C-80EB-4F17-A5B4-3D8A25075146</code></td>
<td style="text-align: right;">71</td>
<td>retained</td>
<td>Dense urban networks create many nearby candidates.</td>
</tr>
<tr class="odd">
<td>Lower-confidence retained snap</td>
<td><code>2023010445298</code></td>
<td style="text-align: right;">2023</td>
<td>weighted</td>
<td style="text-align: right;">0.680</td>
<td style="text-align: right;">7.4 m</td>
<td><code>F5232992-2B80-43BB-ACED-ECA1538996AB</code></td>
<td style="text-align: right;">135</td>
<td>retained</td>
<td>Retained because it passes the threshold; uncertainty is higher.</td>
</tr>
<tr class="even">
<td>Filtered low-score snap</td>
<td><code>2015950000240</code></td>
<td style="text-align: right;">2015</td>
<td>weighted</td>
<td style="text-align: right;">0.596</td>
<td style="text-align: right;">25.3 m</td>
<td><code>E2DE2F6D-9788-4273-9848-86AA8B014DAD</code></td>
<td style="text-align: right;">40</td>
<td>filtered</td>
<td>Filtered example: below the retained score threshold.</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-simple.png" class="img-fluid figure-img" alt="Simple STATS19 snapping example showing nearby grey road links, a red selected road link, and a blue collision point."></p>
<figcaption>Simple road segment snap: the point is close to one plausible single-carriageway link.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=2022501162401</code>; 2022-04-04 07:59; severity Slight; first road A38; single carriageway; 50 mph; not at junction; raining; wet surface; point (-4.349419, 50.407907).</p>
<p><strong>What this shows:</strong> The ambiguity is limited here: the collision point sits close to one plausible single-carriageway link, and the next nearby candidates are much farther away. The snap chooses the red A-road link, which is plausible because both distance and road class support it. Confidence is high, although it is still a spatial linkage rather than ground truth. This collision is retained and later counted under its selected <code>link_id × year</code>.</p>
<p><strong>Worked scoring breakdown (reconstructed):</strong> The selected link is not chosen by distance alone. Each nearby candidate is scored on distance, road class, junction/form-of-way agreement, and road-number agreement; the highest composite score is selected. These reconstructed composites use line-to-point distances in the figure window, so the selected-row composite can differ slightly from the saved snap score in the traceability table.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Candidate</th>
<th>Role</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Spatial</th>
<th style="text-align: right;">Class</th>
<th style="text-align: right;">Junction</th>
<th style="text-align: right;">Number</th>
<th style="text-align: right;">Composite</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rank 1</td>
<td>Selected link</td>
<td style="text-align: right;">1.5 m</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.871</td>
<td>Closest plausible A38 link.</td>
</tr>
<tr class="even">
<td>Rank 2</td>
<td>Alternative 2</td>
<td style="text-align: right;">146.2 m</td>
<td style="text-align: right;">0.363</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.620</td>
<td>Same road evidence, but much weaker spatial support.</td>
</tr>
<tr class="odd">
<td>Rank 3</td>
<td>Alternative 3</td>
<td style="text-align: right;">146.2 m</td>
<td style="text-align: right;">0.363</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.620</td>
<td>Similar to candidate 2, so distance separates it from the selected link.</td>
</tr>
</tbody>
</table>
<p>Here, candidates 2 and 3 match the road number and class, but their spatial score is much lower. The selected link wins because it is both the right road class/number and much closer to the collision point.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-junction.png" class="img-fluid figure-img" alt="Roundabout STATS19 snapping example with nearby candidate road links, a selected red roundabout link, and a blue collision point."></p>
<figcaption>Junction or roundabout snap: several short links are plausible, so the selected link is a local spatial decision.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=20171341K0936</code>; 2017-01-20 12:00; severity Slight; first road A650; road type roundabout; 60 mph; <code>junction_detail=0</code>; dry surface; point (-1.520043, 53.708393).</p>
<p><strong>What this shows:</strong> The ambiguity is the junction itself: several short roundabout or approach links are close enough to be plausible. The snap chooses one roundabout link, which is plausible because the point lies on the junction geometry and the form-of-way matches the junction context. Confidence is lower than on an open segment because adjacent junction links can be almost tied. The retained snap contributes one collision to the selected link-year.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-parallel-links.png" class="img-fluid figure-img" alt="Dual carriageway snapping example with parallel nearby candidate links, a selected red link, and a blue collision point."></p>
<figcaption>Dual carriageway or parallel-link snap: nearby links can be close enough that attributes matter as well as distance.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=2018200265540</code>; 2018-01-23 14:35; severity Slight; first road A4540; second road A38; road type roundabout; 40 mph; wet surface; point (-1.888107, 52.491773).</p>
<p><strong>What this shows:</strong> The ambiguity is the cluster of near-parallel and junction links around the point. The snap chooses the red dual-carriageway link; this is plausible because it is colocated with the point and matches the broad road context. It is not a perfect carriageway-level assertion: nearby links have very similar geometry, so confidence depends on the combined score rather than distance alone. The collision is retained and aggregated to the selected link-year.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-dense-urban.png" class="img-fluid figure-img" alt="Dense urban network snapping example with many nearby grey road links, a selected red link, and a blue collision point."></p>
<figcaption>Dense urban snap: many local links sit within a small search window around the point.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=2019051912399</code>; 2019-09-19 18:00; severity Slight; first road unclassified; single carriageway; 30 mph; <code>junction_detail=13</code>; dry surface; point (-3.038868, 53.430502).</p>
<p><strong>What this shows:</strong> The ambiguity is network density. Many short urban links are close to the collision point, and more than one reconstructed nearby candidate can score similarly. The snap chooses an unclassified single-carriageway link, which is plausible because it is at the point and matches the recorded road context. Confidence is still qualified by the dense street pattern. The retained collision is counted on that selected link-year before traffic and context features are joined.</p>
<p><strong>Worked scoring breakdown (reconstructed):</strong> Dense urban examples are useful because they show the limit of the method as well as the method itself: several short links can receive near-identical evidence.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Candidate</th>
<th>Role</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Spatial</th>
<th style="text-align: right;">Class</th>
<th style="text-align: right;">Junction</th>
<th style="text-align: right;">Number</th>
<th style="text-align: right;">Composite</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rank 2</td>
<td>Selected link</td>
<td style="text-align: right;">0.0 m</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.950</td>
<td>Saved snap target; all non-number evidence is strong.</td>
</tr>
<tr class="even">
<td>Rank 1</td>
<td>Alternative 2</td>
<td style="text-align: right;">0.0 m</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.950</td>
<td>Reconstructs as tied, showing genuine local ambiguity.</td>
</tr>
<tr class="odd">
<td>Rank 3</td>
<td>Alternative 3</td>
<td style="text-align: right;">38.1 m</td>
<td style="text-align: right;">0.768</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.857</td>
<td>Still plausible, but less spatially supported.</td>
</tr>
</tbody>
</table>
<p>Here, the selected link and candidate 2 reconstruct as a tie: the method has found a plausible top-scoring local link, but it should not be read as a perfect carriageway-level truth. Candidate 3 is also plausible, but lower distance support drops its composite score.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-low-confidence.png" class="img-fluid figure-img" alt="Lower-confidence STATS19 snapping example showing a dense road network, selected red link, and blue collision point."></p>
<figcaption>Lower-confidence retained snap: the selected link is retained but carries a lower composite score for downstream filtering and diagnostics.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=2023010445298</code>; 2023-05-26 19:03; severity Slight; first road class C with no road number; single carriageway; 20 mph; not at junction; dry surface; point (-0.249922, 51.516427).</p>
<p><strong>What this shows:</strong> This is lower confidence because the point is surrounded by many nearby links and the selected score is only just above the retention threshold. The snap chooses the closest unclassified single-carriageway link, which is plausible spatially, but nearby alternatives mean the exact road assignment is less certain. Because the score remains above 0.6, the collision is retained and included in the downstream <code>link_id × year</code> collision count.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../outputs/figures/snap-example-filtered-low-score.png" class="img-fluid figure-img" alt="Filtered low-score STATS19 snapping example showing nearby candidate links, the selected weighted link, and the collision point."></p>
<figcaption>Filtered low-score snap: the selected weighted link is shown, but the score falls below the retention threshold used for aggregation.</figcaption>
</figure>
</div>
<p><strong>Original STATS19 row:</strong> <code>collision_index=2015950000240</code>; 2015-01-22 08:05; severity Serious; first road B1345; single carriageway; 60 mph; not at junction; wet surface; point (-2.746766, 56.055312).</p>
<p><strong>What this shows:</strong> The ambiguity is both spatial and attribute-based: the selected link is close to the point, but the saved weighted score falls below 0.6 after combining distance, road class, junction context, and road-number evidence. The red link is the best weighted snap stored for this collision, but confidence is too low for the modelling target. This collision is filtered out before link-year aggregation, so it does not add to any road-link collision count used for rate modelling.</p>
</section>
<section id="fallback-snap_quick-and-snap_collisions_to_roads" class="level3" data-number="5.8">
<h3 data-number="5.8" class="anchored" data-anchor-id="fallback-snap_quick-and-snap_collisions_to_roads"><span class="header-section-number">5.8</span> Fallback: <code>snap_quick</code> and <code>snap_collisions_to_roads</code></h3>
<p><code>snap.py</code> also provides <code>snap_quick</code> — a single <code>sjoin_nearest</code> call with a configurable cap (default 500 m). No scoring. It exists as a <strong>baseline</strong> for comparing against the weighted approach via <code>compare_snaps()</code>, and as a <strong>fast option</strong> for pipeline iteration where snap precision isn’t the current concern.</p>
<p>If <code>snapped_weighted.parquet</code> is not available, <code>join.py</code> falls back to <code>snap_collisions_to_roads()</code> — an attribute-match-then-spatial pipeline that predates <code>snap_weighted</code>. It’s kept only for regeneration and should not be used for production runs.</p>
<hr>
</section>
</section>
<section id="stage-3-webtris-aadf" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="stage-3-webtris-aadf"><span class="header-section-number">6</span> Stage 3: WebTRIS → AADF</h2>
<p>WebTRIS sensors are point locations on motorways and major A-roads. AADF count points are also points. Neither has a shared ID — the link is spatial.</p>
<p><code>_attach_webtris_to_aadf()</code> runs a per-year nearest-neighbour join from AADF points to WebTRIS sites using <code>geopandas.sjoin_nearest</code> with <code>max_distance = 5000 m</code>. Beyond 5 km, WebTRIS features are <strong>nulled</strong> rather than retaining the nearest-but-far match.</p>
<p>The per-year scoping matters: a 2019 WebTRIS reading only attaches to the 2019 AADF row, not to adjacent years. This keeps temporal alignment clean but means WebTRIS columns are NaN for AADF years outside the WebTRIS pull window (2019, 2021, 2023).</p>
<section id="why-nullify-beyond-the-cap" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="why-nullify-beyond-the-cap"><span class="header-section-number">6.1</span> Why nullify beyond the cap?</h3>
<p>An alternative would be to keep the nearest WebTRIS match regardless of distance. This is rejected because:</p>
<ul>
<li>Beyond 5 km, the sensor and the count point are likely on different corridors with different traffic composition.</li>
<li>A “nearest” match that is actually irrelevant is worse than missing data — it adds noise that looks like signal to the model.</li>
</ul>
<p>NaN is the honest representation of “no nearby sensor”.</p>
<hr>
</section>
</section>
<section id="stage-4-aadf-road-links" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="stage-4-aadf-road-links"><span class="header-section-number">7</span> Stage 4: AADF → road links</h2>
<p>Attaching AADF traffic counts to OS Open Roads links is run per year, again via <code>sjoin_nearest</code>. The distance is measured from <strong>each road link’s centroid</strong> to the nearest AADF count point.</p>
<section id="distance-cap-2-km" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="distance-cap-2-km"><span class="header-section-number">7.1</span> Distance cap: 2 km</h3>
<p>Beyond 2 km, the count point is treated as not representative of the link. Features are set to NaN rather than retained. In practice this means:</p>
<ul>
<li>Motorway and major A-road links almost always have AADF attached (count points are dense on these roads).</li>
<li>Minor rural roads frequently have NaN traffic — no count point is close enough.</li>
</ul>
</section>
<section id="street-name-fallback" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="street-name-fallback"><span class="header-section-number">7.2</span> Street-name fallback</h3>
<p>For links beyond the 2 km cap that have a <code>street_name_clean</code>, a secondary name-match is attempted against AADF <code>road_name_clean</code>. This recovers named minor roads (e.g.&nbsp;residential streets with a count point more than 2 km away along the same named road).</p>
<p>Matches recovered this way are tagged <code>aadf_join_method = 'name_match'</code> so they can be identified separately from spatial matches.</p>
</section>
<section id="what-this-means-for-the-model" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="what-this-means-for-the-model"><span class="header-section-number">7.3</span> What this means for the model</h3>
<p>Minor-road links typically have <code>aadf_available = False</code>, which means:</p>
<ul>
<li>No <code>collision_rate_per_mvkm</code> (no denominator)</li>
<li>No HGV percentage features</li>
<li><code>has_rate = False</code> — these rows can be filtered out of rate modelling</li>
</ul>
<p>This is a deliberate choice over imputing a fake flow value. Minor-road rate modelling requires a separate AADT estimation step, which is out of scope for the current joining pipeline.</p>
<hr>
</section>
</section>
<section id="stage-5-aggregation-to-link-year" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="stage-5-aggregation-to-link-year"><span class="header-section-number">8</span> Stage 5: Aggregation to link × year</h2>
<p><code>build_road_link_annual()</code> produces the final modelling table.</p>
<section id="filtering-snapped-collisions" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="filtering-snapped-collisions"><span class="header-section-number">8.1</span> Filtering snapped collisions</h3>
<p>Only collisions with <code>snap_method in ['weighted', 'attribute', 'spatial']</code> are included, and if <code>snap_score</code> is available the <code>&gt;= 0.6</code> threshold is applied. Collisions marked <code>invalid_coords</code> or <code>unmatched</code> are excluded from the rate calculation but their counts are available separately.</p>
</section>
<section id="per-link-aggregation" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="per-link-aggregation"><span class="header-section-number">8.2</span> Per-link aggregation</h3>
<p>For each <code>link_id × year</code> group:</p>
<ul>
<li><code>collision_count</code> — total injury collisions snapped to the link</li>
<li><code>fatal_count</code>, <code>serious_count</code>, <code>slight_count</code> — severity breakdown</li>
<li><code>casualty_count</code> — sum of casualties across the collisions</li>
<li><code>hgv_collision_count</code> — collisions where any involved vehicle has <code>vehicle_type</code> in <code>{19, 20, 21}</code></li>
<li><code>mean_vehicles_per_collision</code> — proxy for collision complexity</li>
</ul>
</section>
<section id="joining-road-attributes" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="joining-road-attributes"><span class="header-section-number">8.3</span> Joining road attributes</h3>
<p>OS Open Roads metadata (<code>road_classification</code>, <code>road_function</code>, <code>form_of_way</code>, <code>link_length_km</code>, <code>is_trunk</code>, <code>is_primary</code>) is joined onto the aggregated table via <code>link_id</code>. This is a direct key join — no spatial logic.</p>
</section>
<section id="final-rate-calculation" class="level3" data-number="8.4">
<h3 data-number="8.4" class="anchored" data-anchor-id="final-rate-calculation"><span class="header-section-number">8.4</span> Final rate calculation</h3>
<pre><code>vehicle_km              = all_motor_vehicles × link_length_km × 365
collision_rate_per_mvkm = collision_count / (vehicle_km / 1e6)</code></pre>
<p>Rate is NaN where <code>all_motor_vehicles</code> is NaN (see Stage 4). The <code>has_rate</code> flag in <code>features.py</code> makes this explicit.</p>
<hr>
</section>
</section>
<section id="quality-tracking" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="quality-tracking"><span class="header-section-number">9</span> Quality tracking</h2>
<p>Several confidence fields propagate from the joining pipeline into the feature table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>snap_score</code></td>
<td>Composite score 0–1 from weighted snap</td>
</tr>
<tr class="even">
<td><code>score_spatial</code>, <code>score_class</code>, <code>score_junction</code>, <code>score_number</code></td>
<td>Per-dimension breakdown for diagnostics</td>
</tr>
<tr class="odd">
<td><code>snap_method</code></td>
<td><code>weighted</code> / <code>spatial</code> / <code>unmatched</code> / <code>invalid_coords</code></td>
</tr>
<tr class="even">
<td><code>snap_distance_m</code></td>
<td>Metres from collision to snapped link</td>
</tr>
<tr class="odd">
<td><code>aadf_snap_distance_m</code></td>
<td>Metres from link centroid to matched count point</td>
</tr>
<tr class="even">
<td><code>aadf_join_method</code></td>
<td><code>spatial</code> or <code>name_match</code></td>
</tr>
<tr class="odd">
<td><code>aadf_available</code>, <code>webtris_available</code></td>
<td>Boolean flags for downstream filtering</td>
</tr>
</tbody>
</table>
<p>The per-dimension scores are particularly useful for diagnosing where the weighted snap is making compromises — a link-year with <code>mean(score_spatial) = 0.9</code> and <code>mean(score_class) = 0.4</code> is saying “I’m confident about the geometry but the attribute match is weak”, which is exactly the kind of signal that should reduce confidence in any rate derived from those collisions.</p>
<hr>
</section>
<section id="quick-vs-weighted-comparison" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="quick-vs-weighted-comparison"><span class="header-section-number">10</span> Quick-vs-weighted comparison</h2>
<p><code>compare_snaps()</code> runs both methods on the same collisions and reports agreement rate, per-link-id disagreements, and weighted-only matches. This is the standard QA step when changing any scoring parameter — the diff against <code>snap_quick</code> tells you what the scoring is actually doing relative to pure proximity.</p>
<p>Typical observations from the Yorkshire pilot:</p>
<ul>
<li>Agreement is high on motorways and major A-roads (separated carriageways aside), where the nearest link is almost always the correct one.</li>
<li>Disagreement concentrates on urban areas with parallel A / B / minor roads, and at junctions where slip roads sit close to the main carriageway.</li>
<li>Weighted-only matches occur when the nearest link is beyond the quick-snap 500 m cap but within 500 m of a same-class alternative — these are rare but legitimate.</li>
</ul>
<hr>
</section>
<section id="known-issues-and-tradeoffs" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="known-issues-and-tradeoffs"><span class="header-section-number">11</span> Known issues and tradeoffs</h2>
<section id="weights-are-fixed-not-learned" class="level3" data-number="11.1">
<h3 data-number="11.1" class="anchored" data-anchor-id="weights-are-fixed-not-learned"><span class="header-section-number">11.1</span> Weights are fixed, not learned</h3>
<p>The 40/25/25/10 split across spatial/class/junction/number is a design choice. No formal optimisation has been run against a labelled validation set. The weights feel broadly right — spatial dominates, attributes act as a tiebreaker, road number is down-weighted because of its known quality issues — but this is engineering judgement, not a fitted parameter.</p>
</section>
<section id="distance-caps-are-empirical" class="level3" data-number="11.2">
<h3 data-number="11.2" class="anchored" data-anchor-id="distance-caps-are-empirical"><span class="header-section-number">11.2</span> Distance caps are empirical</h3>
<p>The 100 m half-life, 500 m search radius, 2 km AADF cap, and 5 km WebTRIS cap are all engineering choices. Tighter caps increase precision but reduce coverage. No sensitivity analysis has been run.</p>
</section>
<section id="error-compounding-across-stages" class="level3" data-number="11.3">
<h3 data-number="11.3" class="anchored" data-anchor-id="error-compounding-across-stages"><span class="header-section-number">11.3</span> Error compounding across stages</h3>
<p>Joins are chained: WebTRIS→AADF→link. A 4 km WebTRIS match plus a 1.8 km AADF match means the WebTRIS sensor is effectively 5+ km from the road link. The individual caps don’t bound the total separation. In practice this mostly affects minor roads that already have <code>aadf_available = False</code>, so the compounding is concentrated where the data is least used anyway.</p>
</section>
<section id="road-name-normalisation-is-strict" class="level3" data-number="11.4">
<h3 data-number="11.4" class="anchored" data-anchor-id="road-name-normalisation-is-strict"><span class="header-section-number">11.4</span> Road name normalisation is strict</h3>
<p><code>road_name_clean</code> is an uppercased whitespace-stripped match. “M62” matches “M 62” (after cleaning) but not “M062” or “M62 Westbound”. Non-standard road name encoding silently fails the road number score — it falls through to the spatial + class + junction components, which usually still yield a correct match but with a lower composite score.</p>
</section>
<section id="dual-carriageways" class="level3" data-number="11.5">
<h3 data-number="11.5" class="anchored" data-anchor-id="dual-carriageways"><span class="header-section-number">11.5</span> Dual carriageways</h3>
<p>OS Open Roads represents dual carriageways as two separate links. Nearest-neighbour can snap a collision to the wrong carriageway, particularly on motorways where GPS drift + narrow carriageway separation produce ambiguous cases. The weighted snap does not distinguish between carriageways — both have the same <code>road_name_clean</code> and usually the same <code>road_classification</code> and <code>form_of_way</code>, so the composite score is nearly tied.</p>
</section>
<section id="coordinate-source-limitations" class="level3" data-number="11.6">
<h3 data-number="11.6" class="anchored" data-anchor-id="coordinate-source-limitations"><span class="header-section-number">11.6</span> Coordinate-source limitations</h3>
<p>STATS19 lat/lon is reliable but not perfectly accurate — drift of 20–50 m is normal. The 100 m spatial half-life was chosen with this in mind: a correct match at 50 m still scores 0.71, which is high enough to dominate if the attribute scores are at least neutral.</p>
<hr>
</section>
</section>
<section id="next-steps" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="next-steps"><span class="header-section-number">12</span> Next steps</h2>
<p>The joined table feeds into:</p>
<ul>
<li><code>features.py</code> — rate calculation, log-transforms, temporal features, lag features.</li>
<li><code>model/collision.py</code> — regression on <code>collision_rate_per_mvkm</code>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/openroadrisk\.org\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Open Road Risk</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>